version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  avantrip-react:
    image: node:6
    ports:
      - 3899
    working_dir: /app
    volumes:
      - ./:/app/
    environment:
      - VIRTUAL_HOST=avantrip-react.localhost.dev
    command: sh -c "npm i && npm run build-storybook && npm run start"
    
