export default {
  colors:{
    brand:'#e1020a',
    primary:'#0192d5',
    secondary:'#0192d5',
    alert:'#F90',
    success:'#3f9f10',
    warning:'#F90',
    danger:'#F90',
    white:'#FFF',
    gray:'#efefef',
    darkgray:'#ccc'
  },
  texts:{
    hxxl:{
      size:'40px',
      weight:'normal',
      family:'Arial'
    },
    xxl:{
      size:'36px',
      weight:'normal',
      family:'Arial'
    },
    xl:{
      size:'28px',
      weight:'normal',
      family:'Arial'
    },
    l:{
      size:'22px',
      weight:'normal',
      family:'Arial'
    },
    m:{
      size:'16px',
      weight:'normal',
      family:'Arial'
    },
    s:{
      size:'14px',
      weight:'normal',
      family:'Arial'
    },
    xs:{
      size:'12px',
      weight:'normal',
      family:'Arial'
    },
  },
  buttons:{
    cta:{
      normal:{
        bgc:'brand',
        color:'white',
        fontSize:'20px',
      }
    },
    scta:{
      normal:{
        bgc:'primary',
        color:'white',
        fontSize:'20px',
      }
    },
    ghst:{
      normal:{
        bgc:'secondary',
        color:'white',
        fontSize:'20px',
      }
    },
    link:{
      normal:{
        bgc:'alert',
        color:'white',
        fontSize:'20px',
      }
    }
  }
}
