export default {
  colors:{
    brand:'#ff6600',
    primary:'#333',
    secondary:'#c11127',
    alert:'#F90',
    success:'#3f9f10',
    warning:'#F90',
    danger:'#F90',
  },
  texts:{
    hxxl:{
      size:'40px',
      weight:'300'
    },
    xxl:{
      size:'36px',
      weight:'300'
    },
    xl:{
      size:'28px',
      weight:'900'
    },
    l:{
      size:'22px',
      weight:'500'
    },
    m:{
      size:'18px',
      weight:'300'
    },
    s:{
      size:'13px',
      weight:'300'
    },
    xs:{
      size:'12px',
      weight:'300'
    }
  },
  buttons:{
    cta:{
      normal:{
        bgc:'brand',
        color:'white',
        fontSize:'16px',
      }
    },
    scta:{
      normal:{
        bgc:'primary',
        color:'white',
        fontSize:'16px',
      }
    },
    ghst:{
      normal:{
        bgc:'secondary',
        color:'white',
        fontSize:'16px',
      }
    },
    link:{
      normal:{
        bgc:'alert',
        color:'white',
        fontSize:'16px',
      }
    }
  },
  viewport:{
    desktop: '1280px'
  }
}
