export default {
  colors:{
    brand:'#ff6600',
    primary:'#333',
    secondary:'#c11127',
    alert:'#e90010',
    success:'#3f9f10',
    warning:'#e90010',
    danger:'#e90010',
    white:'#FFF',
    gray:'#efefef',
    darkgray:'#999',
    darkergray:'#666',
    blue: '#2A3069'
  },
  texts:{
    hxxl:{
      size:'40px',
      weight:'300'
    },
    xxl:{
      size:'36px',
      weight:'300'
    },
    xl:{
      size:'28px',
      weight:'900'
    },
    l:{
      size:'22px',
      weight:'500'
    },
    m:{
      size:'18px',
      weight:'300'
    },
    s:{
      size:'14px',
      weight:'300'
    },
    xs:{
      size:'12px',
      weight:'300'
    }
  },
  buttons:{
    cta:{
      normal:{
        bgc:'brand',
        color:'white',
        fontSize:'20px',
      }
    },
    scta:{
      normal:{
        bgc:'primary',
        color:'white',
        fontSize:'20px',
      }
    },
    ghst:{
      normal:{
        bgc:'secondary',
        color:'white',
        fontSize:'20px',
      }
    },
    link:{
      normal:{
        bgc:'alert',
        color:'white',
        fontSize:'20px',
      }
    }
  },
  fonts:{
    main: 'Stag-Sans'
  }
}
